name: CI

on: [push, pull_request]

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Verify v fmt
        run: |
          v fmt -verify .

  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Symlink to ~/.vmodules
        run: |
          mkdir -p ~/.vmodules/
          ln -s $PWD ~/.vmodules/

      - name: Install dependencies
        run: sudo apt-get install --quiet -y libssl-dev

      - name: Build ping-pong example
        run: |
          v ./examples/ping-pong/main.v
      - name: Build send-embed example
        run: |
          v ./examples/send-embed/main.v
      - name: Build upload-image example
        run: |
          v ./examples/upload-image/main.v
